### ISSUE TITLE
[FEATURE] Greenplum 7 Support

### ISSUE THREAD

**Issue by RealGrayRabbit** [HashDataInc/cbcopy#5]
### Describe the feature

Currently cbcopy only support GP5,GP6. But we have clients using Greenplum 7. Could you help to add support for GP7？Our clients need this function urgently.

### Motivation

Our clients need this function urgently.

**Comment by robertmu** [comment]
Thank you for raising this issue about Greenplum 7 support!

Let me clarify the current version support status of cbcopy:
- GPDB 4.x - Minimum version 4.3.17 required
- GPDB 5.x - All versions supported
- GPDB 6.x - All versions supported
- CBDB 1.x - All versions supported

We understand this is an urgent requirement for your clients. We will add Greenplum 7 support to our development roadmap with high priority.
