### ISSUE TITLE
[Bug] greenplum 6.26  cbcopy  migration   cloudberry1.6 error

### ISSUE THREAD

**Issue by SwapEnergi** [HashDataInc/cbcopy#6]
### Cloudberry Database and cbcopy version

greenplum 2.6 
cloudberry 1.6

### What happened

20241119:09:23:08 cbcopy:gpadmin:swap-cloudberry:243876-[ERROR]:-[Worker 0] Failed to copy table "test.ads_holder": ERROR: could not write to COPY program: Broken pipe (copy.c:673) (SQLSTATE XX000)
20241119:09:23:08 cbcopy:gpadmin:swap-cloudberry:243876-[ERROR]:-[Worker 1] Failed to copy table "test.ads_top10": ERROR: could not write to COPY program: Broken pipe (copy.c:673) (SQLSTATE XX000)
Pre-data objects restored:  (97/248) [======================>-----------------------------------] 39 %
Pre-data objects restored:  (111/248) [=========================>--------------------------------] 45 %
Pre-data objects restored:  (112/248) [=========================>--------------------------------] 45 %
Table copied:  (3/74942) [----------------------------------------------------------] 0 %
20241119:09:23:11 cbcopy:gpadmin:swap-cloudberry:243876-[ERROR]:-[Worker 0] Failed to copy table "test.ads_housing": ERROR: could not write to COPY program: Broken pipe (copy.c:673) (SQLSTATE XX000)
Pre-data objects restored:  (112/248) [=========================>--------------------------------] 45 %
Table copied:  (5/74942) [----------------------------------------------------------] 0 %
Pre-data objects restored:  (112/248) [=========================>--------------------------------] 45 %
Table copied:  (6/74942) [----------------------------------------------------------] 0 %
20241119:09:23:14 cbcopy:gpadmin:swap-cloudberry:243876-[ERROR]:-[Worker 0] Failed to copy table "test.ads_wd": ERROR: could not write to COPY program: Broken pipe (copy.c:673) (SQLSTATE XX000)
Pre-data objects restored:  (112/248) [=========================>--------------------------------] 45 %
Table copied:  (8/74942) [----------------------------------------------------------] 0 %
panic: runtime error: index out of range [0] with length 0

goroutine 232 [running]:
github.com/cloudberrydb/cbcopy/copy.(*ExtDestLtCopy).formClientNumbers(0xc002c6dae0)
	/usr/src/cbcopy/copy/copy_command.go:453 +0x3a5
github.com/cloudberrydb/cbcopy/copy.(*ExtDestLtCopy).CopyFrom(0xc002c6dae0, 0xc000263d10, {0xb69850, 0xc002c6db30}, {{0xc0003aa540, 0x6}, {0xc0003aa550, 0xf}, 0x0, 0x0}, ...)
	/usr/src/cbcopy/copy/copy_command.go:511 +0xe9
github.com/cloudberrydb/cbcopy/copy.(*CopyOperation).executeCopyFrom(0x444efb?, 0xc000052fd0?, 0xc00f4b4158, 0xc00053b820)
	/usr/src/cbcopy/copy/copy_operation.go:52 +0xda
created by github.com/cloudberrydb/cbcopy/copy.(*CopyOperation).Execute in goroutine 8
	/usr/src/cbcopy/copy/copy_operation.go:119 +0xf5

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by robertmu** [comment]
- Which version of cbcopy are you using? You can get the version by running cbcopy --version
- You can paste the cbcopy log file here. The log file is located at the following path: $HOME/gpAdminlogs/cbcopy_$timestamp.log
- You need to provide the number of segments for both the source and target databases

**Comment by robertmu** [comment]
Thank you for reporting this issue. After investigating the error logs and the code, I've identified the root cause:

The error occurs because the target database has no active segment nodes (primary segments). This can be verified by the following query returning empty results:

```sql
SELECT content, hostname
FROM gp_segment_configuration
WHERE role = 'p' AND content != -1 
ORDER BY content;
```

The panic error `index out of range [0] with length 0` happens because cbcopy expects at least one segment node to be present in the target database for data distribution.

To resolve this issue:
1. Please ensure your target database is properly initialized with segment nodes
2. Verify that all segments are up and running
3. Check the `gp_segment_configuration` table to confirm the segment configuration
